// <auto-generated />
using CRM2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CRM2.Migrations
{
    [DbContext(typeof(ManagementContext))]
    partial class ManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("CRM2.Models.Customer", b =>
                {
                    b.Property<int>("Cus_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cus_city");

                    b.Property<string>("Cus_country");

                    b.Property<string>("Cus_email");

                    b.Property<string>("Cus_fname");

                    b.Property<string>("Cus_lname");

                    b.Property<string>("Cus_phone");

                    b.Property<string>("Cus_pro");

                    b.Property<string>("Cus_street");

                    b.Property<int>("Inv_ID");

                    b.HasKey("Cus_ID")
                        .HasName("PrimaryKey_CustomerId");

                    b.HasIndex("Inv_ID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CRM2.Models.Employee", b =>
                {
                    b.Property<int>("Emp_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Cus_ID");

                    b.Property<string>("Emp_email");

                    b.Property<string>("Emp_fname");

                    b.Property<string>("Emp_lname");

                    b.Property<string>("Emp_phone");

                    b.HasKey("Emp_ID")
                        .HasName("PrimaryKey_EmployeeId");

                    b.HasIndex("Cus_ID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("CRM2.Models.Invoice", b =>
                {
                    b.Property<int>("Inv_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Inv_amount");

                    b.Property<DateTime>("Inv_date");

                    b.Property<string>("Inv_des");

                    b.HasKey("Inv_ID")
                        .HasName("PrimaryKey_InvoiceId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("CRM2.Models.Customer", b =>
                {
                    b.HasOne("CRM2.Models.Invoice", "Invoice")
                        .WithMany("Customers")
                        .HasForeignKey("Inv_ID")
                        .HasConstraintName("ForeignKey_Customer_Invoice")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CRM2.Models.Employee", b =>
                {
                    b.HasOne("CRM2.Models.Customer", "Customer")
                        .WithMany("Employees")
                        .HasForeignKey("Cus_ID")
                        .HasConstraintName("ForeignKey_Employee_Customer")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
